import { UserButton } from "@clerk/nextjs";
import Head from "next/head";
import { Button } from "@components/ui/Button";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen  items-center justify-center ">
        <div className="container flex flex-col gap-3 items-center justify-center  ">
          <p>this is main page</p>
          <Button>shadcn button</Button>
          <UserButton afterSignOutUrl="/" />
        </div>
      </main>
    </>
  )
}
