import { UserButton } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { Button } from "~/components/ui/Button";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen  items-center justify-center ">
        <div className="container flex items-center justify-center  ">
          this is main page
          <Button />
          <UserButton afterSignOutUrl="/" />
        </div>
      </main>
    </>
  );
}
